DATA_SOURCE: "TCIA"
DATASET_NAME: "NSCLC-Radiomics_windowed"

### CLINICAL VARIABLE INFORMATION ###
CLINICAL:
    FILE: "NSCLC-Radiomics-Lung1.clinical-version3-Oct-2019.csv"
    OUTCOME_VARIABLES:
        time_label: "Survival.time"
        event_label: "deadstatus.event"
        convert_to_years: True
        event_value_mapping: {}
    INCLUSION_VARIABLES: {}
    EXCLUSION_VARIABLES: {}

### MED-IMAGETOOLS settings
MIT:
    MODALITIES:
        image: CT
        mask: RTSTRUCT
    ROI_STRATEGY: SEPARATE
    ROI_MATCH_MAP: # NOTE: there can be no spaces in KEY:ROI_NAME
        'ROI:GTV-1,gtv-pre-op'

### READII settings
READII:
    IMAGE_TYPES:
        regions:
            - "full"
            - "roi"
            - "non_roi"
        permutations:
            - "shuffled"
            - "randomized"
            - "sampled"
        crop: 
        resize: []

### Feature Extraction settings
EXTRACTION:
    METHOD: pyradiomics
    CONFIG: linear_all_images_features

### Analysis settings
ANALYSIS:
    TRAIN_TEST_SPLIT:
        split: False
        split_variable: {}
        impute: null

RANDOM_SEED: 10

VOL_LINE: 0.5845945756862013
